### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by Bizarrus** [AeonLucid/SteamworksSharp#1]
Can you provide more examples or a documentation?

**Comment by AeonLucid** [comment]
There is an example here https://github.com/AeonLucid/SteamworksSharp/blob/master/SteamworksSharp.Example/Program.cs.
It's just a wrapper for steamworks so further docs can be found at Steam https://partner.steamgames.com/doc/sdk/api.

**Comment by Bizarrus** [comment]
But what is `IntPtr`, i can't found informations to register a callback over `             SteamApi.RegisterCallback(IntPtr pCallback, int iCallback)` to make an request for `UGC`.

**Comment by Bizarrus** [comment]
I had stop using this package.

[Steamworks.NET](https://github.com/rlabrecque/Steamworks.NET) has a better documentation and i've solved here the problem lots of faster.
